language: python

python:
    - 2.6
    - 2.7

branches:
  only:
    - master

install:
  - sudo apt-get update > /dev/null
  - sudo apt-get -q install tarantool

  - mkdir _tarantool_temp
  - cp init.lua _tarantool_temp/
  - tarantool_box -c tarantool.cfg --init-storage
  - tarantool_box -c tarantool.cfg --background

  - pip install . --use-mirrors

notifications:
    email: false

script: trial tests/

git:
  depth: 1
